# Generated by Django 4.1.7 on 2023-09-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('price', models.CharField(max_length=20)),
                ('quantity', models.CharField(default='', max_length=10)),
                ('date', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
